require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe DeliveryTimesController do

  # This should return the minimal set of attributes required to create a valid
  # DeliveryTime. As you add validations to DeliveryTime, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "duration" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # DeliveryTimesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all delivery_times as @delivery_times" do
      delivery_time = DeliveryTime.create! valid_attributes
      get :index, {}, valid_session
      assigns(:delivery_times).should eq([delivery_time])
    end
  end

  describe "GET show" do
    it "assigns the requested delivery_time as @delivery_time" do
      delivery_time = DeliveryTime.create! valid_attributes
      get :show, {:id => delivery_time.to_param}, valid_session
      assigns(:delivery_time).should eq(delivery_time)
    end
  end

  describe "GET new" do
    it "assigns a new delivery_time as @delivery_time" do
      get :new, {}, valid_session
      assigns(:delivery_time).should be_a_new(DeliveryTime)
    end
  end

  describe "GET edit" do
    it "assigns the requested delivery_time as @delivery_time" do
      delivery_time = DeliveryTime.create! valid_attributes
      get :edit, {:id => delivery_time.to_param}, valid_session
      assigns(:delivery_time).should eq(delivery_time)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new DeliveryTime" do
        expect {
          post :create, {:delivery_time => valid_attributes}, valid_session
        }.to change(DeliveryTime, :count).by(1)
      end

      it "assigns a newly created delivery_time as @delivery_time" do
        post :create, {:delivery_time => valid_attributes}, valid_session
        assigns(:delivery_time).should be_a(DeliveryTime)
        assigns(:delivery_time).should be_persisted
      end

      it "redirects to the created delivery_time" do
        post :create, {:delivery_time => valid_attributes}, valid_session
        response.should redirect_to(DeliveryTime.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved delivery_time as @delivery_time" do
        # Trigger the behavior that occurs when invalid params are submitted
        DeliveryTime.any_instance.stub(:save).and_return(false)
        post :create, {:delivery_time => { "duration" => "invalid value" }}, valid_session
        assigns(:delivery_time).should be_a_new(DeliveryTime)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        DeliveryTime.any_instance.stub(:save).and_return(false)
        post :create, {:delivery_time => { "duration" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested delivery_time" do
        delivery_time = DeliveryTime.create! valid_attributes
        # Assuming there are no other delivery_times in the database, this
        # specifies that the DeliveryTime created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        DeliveryTime.any_instance.should_receive(:update).with({ "duration" => "MyString" })
        put :update, {:id => delivery_time.to_param, :delivery_time => { "duration" => "MyString" }}, valid_session
      end

      it "assigns the requested delivery_time as @delivery_time" do
        delivery_time = DeliveryTime.create! valid_attributes
        put :update, {:id => delivery_time.to_param, :delivery_time => valid_attributes}, valid_session
        assigns(:delivery_time).should eq(delivery_time)
      end

      it "redirects to the delivery_time" do
        delivery_time = DeliveryTime.create! valid_attributes
        put :update, {:id => delivery_time.to_param, :delivery_time => valid_attributes}, valid_session
        response.should redirect_to(delivery_time)
      end
    end

    describe "with invalid params" do
      it "assigns the delivery_time as @delivery_time" do
        delivery_time = DeliveryTime.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        DeliveryTime.any_instance.stub(:save).and_return(false)
        put :update, {:id => delivery_time.to_param, :delivery_time => { "duration" => "invalid value" }}, valid_session
        assigns(:delivery_time).should eq(delivery_time)
      end

      it "re-renders the 'edit' template" do
        delivery_time = DeliveryTime.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        DeliveryTime.any_instance.stub(:save).and_return(false)
        put :update, {:id => delivery_time.to_param, :delivery_time => { "duration" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested delivery_time" do
      delivery_time = DeliveryTime.create! valid_attributes
      expect {
        delete :destroy, {:id => delivery_time.to_param}, valid_session
      }.to change(DeliveryTime, :count).by(-1)
    end

    it "redirects to the delivery_times list" do
      delivery_time = DeliveryTime.create! valid_attributes
      delete :destroy, {:id => delivery_time.to_param}, valid_session
      response.should redirect_to(delivery_times_url)
    end
  end

end
